name: morig
channels:
  - pytorch
  - pyg
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py37h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py37h27cfd23_1003
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.14=py37h06a4308_0
  - cffi=1.15.1=py37h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.9=h6a678d5_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py37h295c915_0
  - krb5=1.19.2=hac12032_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.4.0=hecacb30_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib=3.5.2=py37h06a4308_0
  - matplotlib-base=3.5.2=py37hf590b9c_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - networkx=2.6.3=pyhd3eb1b0_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py37h807cd23_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h295c915_0
  - pillow=9.2.0=py37hace64e9_1
  - pip=22.2.2=py37h06a4308_0
  - ply=3.11=py37_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.0.4=py37_torch_1.11.0_cu113
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py37h06a4308_0
  - pyqt=5.15.7=py37h6a678d5_1
  - pyqt5-sip=12.11.0=py37h6a678d5_1
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-louvain=0.15=pyhd3eb1b0_0
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-cluster=1.6.0=py37_torch_1.11.0_cu113
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py37_torch_1.11.0_cu113
  - pytorch-sparse=0.6.14=py37_torch_1.11.0_cu113
  - pytorch-spline-conv=1.2.1=py37_torch_1.11.0_cu113
  - pytz=2022.1=py37h06a4308_0
  - pyyaml=6.0=py37h7f8727e_1
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py37h06a4308_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=63.4.1=py37h06a4308_0
  - sip=6.6.2=py37h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py37h5eee18b_0
  - tqdm=4.64.1=py37h06a4308_0
  - typing_extensions=4.3.0=py37h06a4308_0
  - urllib3=1.26.11=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - yacs=0.1.6=pyhd3eb1b0_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - chardet==5.0.0
    - colorlog==6.7.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dominate==2.7.0
    - entrypoints==0.4
    - fastjsonschema==2.16.2
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - importlib-metadata==5.0.0
    - importlib-resources==5.9.0
    - ipykernel==6.16.0
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jsonschema==4.16.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - lxml==4.9.1
    - mapbox-earcut==1.0.0
    - markdown==3.4.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mpmath==1.2.1
    - msgpack==1.0.4
    - nbclient==0.6.8
    - nbconvert==7.1.0
    - nbformat==5.6.1
    - nest-asyncio==1.5.6
    - notebook==6.4.12
    - oauthlib==3.2.1
    - open3d==0.9.0.0
    - opencv-python-headless==4.6.0.66
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.31
    - protobuf==3.19.6
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycollada==0.7.2
    - pyglet==1.5.27
    - pygments==2.13.0
    - pyrsistent==0.18.1
    - pyzmq==24.0.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - rtree==0.8.3
    - send2trash==1.8.0
    - shapely==1.8.4
    - soupsieve==2.3.2.post1
    - svg-path==6.2
    - sympy==1.10.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.16.0
    - tinycss2==1.1.1
    - traitlets==5.4.0
    - trimesh==3.15.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - xxhash==3.0.0
    - zipp==3.8.1
